board/urls.py
from django.urls import path
from board.views import base_views, question_views, answer_views, vote_views, comment_views, answer_comment_views

app_name = 'board'  #네임 스페이스 설정

urlpatterns = [
    #127.0.0.1:8000/board/
    # 메인 페이지
    path('', base_views.index, name='index'),
    # 질문 목록
    path('boardlist/', base_views.boardlist, name='boardlist'),
    #질문/답변 상세
    path('<int:question_id>/', base_views.detail, name='detail'),
    #질문 등록
    path('question/create/', question_views.question_create, name='question_create'),
    #답변 등록
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    #질문 수정
    path('question/modify/<int:question_id>/', question_views.question_modify,
         name='question_modify'),
    #질문 삭제
    path('question/delete/<int:question_id>/', question_views.question_delete,
         name='question_delete'),
    #답변 수정
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify,
         name='answer_modify'),
    #답변 삭제
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete,
         name='answer_delete'),
    #질문 추천
    path('vote/question/<int:question_id>/', vote_views.vote_question,
         name='vote_question'),
    #답변 추천
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer,
         name='vote_answer'),
    #질문 댓글 등록
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question,
         name='comment_create_question'),
    # 질문 댓글 삭제
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question,
         name='comment_delete_question'),
    # 질문 댓글 수정
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question,
         name='comment_modify_question'),
    # 답변 댓글 등록
    path('comment/create/answer/<int:answer_id>/', answer_comment_views.comment_create_answer,
         name='comment_create_answer'),
    # 답변 댓글 수정
    path('comment/modify/answer/<int:comment_id>/', answer_comment_views.comment_modify_answer,
         name='comment_modify_answer'),
    # 답변 댓글 삭제
    path('comment/delete/answer/<int:comment_id>/', answer_comment_views.comment_delete_answer,
         name='comment_delete_answer'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', base_views.index),   #127.0.0.1:8000
    path('board/', include('board.urls')),
    path('common/', include('common.urls')),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from django.urls import path
from polls import views

app_name = 'poll'

urlpatterns = [
    #설문 조사 메인 - 127.0.0.1:8000/polls
    path('', views.index, name='index'),
    # 설문 상세
    path('<int:pk>/', views.detail, name='detail'),
    # 설문 투표
    path('<int:pk>/vote/', views.vote, name='vote')
]

polls/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=100)
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=100)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render
from polls.models import Question, Choice

def index(request):
    #설문 메인
    question_list = Question.objects.all()
    context = {'question_list':question_list}
    return render(request, 'polls/poll_list.html', context)

def detail(request, pk):
    #설문 상세
    # question = Question.objects.get(id=pk)
    question = Question.objects.get(id=pk)
    context = {'question':question}
    return render(request, 'polls/poll_detail.html', context)

def vote(request, pk):
    #투표하기
    question = Question.objects.get(id=pk)
    try:
        choice = request.POST['choice']  #선택한 내용
        sel_choice = question.choice_set.get(id=choice)
    except:
        context = {'question':question, 'error':'선택을 확인하세요!'}
        return render(request, 'polls/poll_detail.html', context)
    else:
        sel_choice.votes += 1 #1 더하기
        sel_choice.save()     #저장
        context = {'question':question}
        return render(request, 'polls/poll_result.html', context)

templates/polls/poll_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <section>
        <h4 class="border-bottom py-2">투표 하기</h4>
        <div class="card my-3">
            <h5 style="margin:20px 100px 10px;">{{ question.question_text }}</h5>
            <form action="{% url 'poll:vote' question.id %}" method="post"
                  style="width:500px; margin:20px 120px;">
                {% csrf_token %}
                {% if error %}
                <div class="alert alert-danger">
                    * {{ error }}
                </div>
                {% endif %}
                {% for choice in question.choice_set.all %}
                <p style="line-height:1.3rem">
                    <input type="radio" name="choice" id="choice" value="{{ choice.id }}">
                    <label for="choice">{{ choice.choice_text }}</label>
                </p>
                {% endfor %}
                <button type="submit" class="btn btn-success">투표</button>
            </form>
        </div>
    </section>
</div>
{% endblock %}

templates/polls/poll_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <section>
        <h4 class="border-bottom py-2">설문 목록</h4>
        <div class="row">
            {% if question_list %}
                {% for question in question_list %}
                <div class="col-4 my-3">
                    <div class="card">
                        <div class="card-body">
                            <div class="card-text" style="line-height:2rem">
                                {{ question.question_text }}
                            </div>
                            <a href="{% url 'poll:detail' question.id %}"
                               class="btn btn-primary mt-5">투표하기 &raquo;</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <p>설문이 없습니다.</p>
            {% endif %}
        </div>
    </section>
</div>
{% endblock %}

templates/polls/poll_result.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <section>
        <h4 class="border-bottom py-2">투표 결과</h4>
        <div class="card my-3">
            <h5 style="margin:20px 100px 10px;">{{ question.question_text }}</h5>
            <ul style="width:500px; margin:0 100px; padding:0 10px;">
                {% for choice in question.choice_set.all %}
                <li style="margin:20px;">
                    {{ choice.choice_text }} -- {{ choice.votes }}votes
                </li>
                {% endfor %}
            </ul>
            <div style="padding-left:100px;">
                <a href="{% url 'poll:index' %}"
                   class="btn btn-secondary my-4">설문목록 가기</a>
            </div>
        </div>
    </section>
</div>
{% endblock %}