board/urls.py
from django.urls import path
from board.views import base_views, question_views, answer_views, vote_views, comment_views, answer_comment_views

app_name = 'board'  #네임 스페이스 설정

urlpatterns = [
    #127.0.0.1:8000/board/
    # 메인 페이지
    path('', base_views.index, name='index'),
    # 질문 목록
    path('boardlist/', base_views.boardlist, name='boardlist'),
    #질문/답변 상세
    path('<int:question_id>/', base_views.detail, name='detail'),
    #질문 등록
    path('question/create/', question_views.question_create, name='question_create'),
    #답변 등록
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    #질문 수정
    path('question/modify/<int:question_id>/', question_views.question_modify,
         name='question_modify'),
    #질문 삭제
    path('question/delete/<int:question_id>/', question_views.question_delete,
         name='question_delete'),
    #답변 수정
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify,
         name='answer_modify'),
    #답변 삭제
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete,
         name='answer_delete'),
    #질문 추천
    path('vote/question/<int:question_id>/', vote_views.vote_question,
         name='vote_question'),
    #답변 추천
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer,
         name='vote_answer'),
    #질문 댓글 등록
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question,
         name='comment_create_question'),
    # 질문 댓글 삭제
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question,
         name='comment_delete_question'),
    # 질문 댓글 수정
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question,
         name='comment_modify_question'),
    # 답변 댓글 등록
    path('comment/create/answer/<int:answer_id>/', answer_comment_views.comment_create_answer,
         name='comment_create_answer'),
    # 답변 댓글 수정
    path('comment/modify/answer/<int:comment_id>/', answer_comment_views.comment_modify_answer,
         name='comment_modify_answer'),
    # 답변 댓글 삭제
    path('comment/delete/answer/<int:comment_id>/', answer_comment_views.comment_delete_answer,
         name='comment_delete_answer'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', base_views.index),   #127.0.0.1:8000
    path('board/', include('board.urls')),
    path('common/', include('common.urls')),
    path('polls/', include('polls.urls')),
]

board/models.py
from django.contrib.auth.models import User
from django.db import models

class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=100)  #제목 칼럼
    content = models.TextField()                #질문 내용
    create_date = models.DateTimeField()        #질문 작성일
    modify_date = models.DateTimeField(null=True, blank=True)  #질문 수정일
    voter = models.ManyToManyField(User, related_name='voter_question')        #추천수

    def __str__(self):
        return self.subject

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE) #외래키, 제목
    content = models.TextField()          #답변 내용
    create_date = models.DateTimeField()  #답변 작성일
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.content

# Comment 모델 생성
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE) # 댓글 글쓴이
    content = models.TextField()        # 댓글 내용
    create_date = models.DateTimeField() # 작성일
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True,
                                 on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True,
                                 on_delete=models.CASCADE)

board/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from board.models import Question, Answer, Comment
from board.forms import QuestionForm, AnswerForm, CommentForm

def index(request):
    return render(request, 'board/index.html')

def boardlist(request):
    #질문 목록
    #question_list = Question.objects.all()  #db 전체조회

    #페이지 처리
    page = request.GET.get('page', 1)  #127.0.0.1:8000/ 기본 1페이지임
    kw = request.GET.get('kw', '')  # 검색어 가져오기

    #조회
    question_list = Question.objects.order_by('-create_date')#작성일 내림차순
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) | # 제목 검색
            Q(content__icontains=kw) | # 내용 검색
            Q(author__username__icontains=kw) | # 글쓴이 검색
            Q(answer__author__username__icontains=kw) |# 답변 글쓴이
            Q(answer__content__icontains=kw)
        ).distinct()   #유일한 것 검색

    paginator = Paginator(question_list, 10) #페이지당 10개씩 설정
    page_obj = paginator.get_page(page)    #페이지 가져오기
    context = {'question_list':page_obj, 'page':page, 'kw':kw}
    return render(request, 'board/question_list.html', context)

def detail(request, question_id):
    # 질문/답변 상세
    # question = Question.objects.get(id=question_id) #해당 id의 질문
    question = get_object_or_404(Question, pk=question_id)
    #경로에 오류가 있을 때 404로 처리(페이지가 없음)
    return render(request, 'board/detail.html', {'question':question})

@login_required(login_url='common:login') #로그인이 안되어 있으면 로그인 페이지로 이동
def question_create(request):
    #질문 등록
    if request.method == "POST":
        form = QuestionForm(request.POST)   #자료 전달받음(request.POST)
        if form.is_valid():
            question = form.save(commit=False) #가저장(날짜가 없어서 가저장)
            question.create_date = timezone.now() #날짜 시간 저장
            question.author = request.user  #글쓴이에 세션 저장
            question.save()  #실제 저장
            return redirect('board:boardlist') #이동할 경로(앱 네임사용) 저장
    else:
        form = QuestionForm()   #form 객체 생성
    return render(request, 'board/question_form.html', {'form':form})

@login_required(login_url='common:login')
def answer_create(request, question_id):
    #답변 등록
    #question = Question.objects.get(id=question_id) #해당 id의 질문 객체 생성
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST) #입력값 전달받음
        if form.is_valid():
            answer = form.save(commit=False)  #내용만 저장됨
            answer.create_date = timezone.now() #작성일
            answer.author = request.user #세션 발급
            answer.question = question  #외래키 질문 저장
            answer.save()
            return redirect('board:detail', question_id=question.id)
    else:
        form= AnswerForm()
    context = {'question':question,'form':form}
    return render(request, 'board/detail.html', context)

@login_required(login_url='common:login')
def question_modify(request, question_id):
    #질문 수정
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)  #수정된 질문 가저장
            question.author = request.user      #세션 발급
            question.modify_date = timezone.now() #수정일
            question.save()
            return redirect('board:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)  #instance를 쓰면 폼에 내용이 채워짐
    return render(request, 'board/question_form.html', {'form':form})

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    #답변 수정
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.author = request.user
            answer.save()
            return redirect('board:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    return render(request, 'board/answer_form.html', {'form':form})

@login_required(login_url='common:login')
def question_delete(request, question_id):
    #질문 삭제
    question = get_object_or_404(Question, pk=question_id)
    question.delete() #질문 삭제
    return redirect('board:index')

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    #답변 삭제
    answer = get_object_or_404(Answer, pk=answer_id)
    answer.delete()
    return redirect('board:detail', question_id=answer.question.id)

@login_required(login_url='common:login')
def vote_question(request, question_id):
    #질문 추천
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        question.voter.add(request.user)    # 추천 추가(로그인한 사람)
    return redirect('board:detail', question_id)

@login_required(login_url='common:login')
def vote_answer(request, answer_id):
    #답변 추천
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        answer.voter.add(request.user)    # 추천 추가(로그인한 사람)
    return redirect('board:detail', question_id=answer.question.id)

@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    # 질문 댓글 등록
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = CommentForm(request.POST) #입력된 댓글 내용
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user   # 세션 권한
            comment.create_date = timezone.now()
            comment.question = question     # 참조 외래키
            comment.save()              # 실제 저장
            return redirect('board:detail', question_id=question_id)
    else:   # GET은 빈 폼을 가져옴
        form = CommentForm()
    context = {'form':form}
    return render(request, 'board/comment_form.html', context)

@login_required(login_url='common:login')
def comment_delete_question(request, comment_id):
    # 질문 댓글 삭제
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.delete()
    return redirect('board:detail', question_id=comment.question.id)

@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    # 질문 댓글 수정
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment) #변경된 내용 입력
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user  # 세션 권한
            comment.modify_date = timezone.now()
            comment.save()  # 실제 저장
            return redirect('board:detail', question_id=comment.question.id)
    else:
        form = CommentForm(instance=comment)    #채워진 폼
    context = {'form':form}
    return render(request, 'board/comment_form.html', context)

board/views/answer_comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from board.models import Question, Answer, Comment
from board.forms import QuestionForm, AnswerForm, CommentForm

@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    # 답변 댓글 등록
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = CommentForm(request.POST) #입력된 댓글 내용
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user   # 세션 권한
            comment.create_date = timezone.now()
            comment.answer = answer     # 참조 외래키
            comment.save()              # 실제 저장
            return redirect('board:detail', question_id=comment.answer.question.id)
    else:   # GET은 빈 폼을 가져옴
        form = CommentForm()
    context = {'form':form}
    return render(request, 'board/comment_form.html', context)

@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
    # 답변 댓글 삭제
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('board:detail', question_id=comment.answer.question.id)
    else:
        comment.delete()
    return redirect('board:detail', question_id=comment.answer.question.id)

@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
    # 답변 댓글 수정
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('board:detail', question_id=comment.answer.question.id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment) #변경된 내용 입력
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user  # 세션 권한
            comment.modify_date = timezone.now()
            comment.save()  # 실제 저장
            return redirect('board:detail', question_id=comment.answer.question.id)
    else:
        form = CommentForm(instance=comment)    #채워진 폼
    context = {'form':form}
    return render(request, 'board/comment_form.html', context)

board/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from board.models import Question, Answer, Comment
from board.forms import QuestionForm, AnswerForm, CommentForm

@login_required(login_url='common:login')
def answer_create(request, question_id):
    #답변 등록
    #question = Question.objects.get(id=question_id) #해당 id의 질문 객체 생성
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST) #입력값 전달받음
        if form.is_valid():
            answer = form.save(commit=False)  #내용만 저장됨
            answer.create_date = timezone.now() #작성일
            answer.author = request.user #세션 발급
            answer.question = question  #외래키 질문 저장
            answer.save()
            return redirect('board:detail', question_id=question.id)
    else:
        form= AnswerForm()
    context = {'question':question,'form':form}
    return render(request, 'board/detail.html', context)

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    #답변 수정
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.author = request.user
            answer.save()
            return redirect('board:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    return render(request, 'board/answer_form.html', {'form':form})

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    #답변 삭제
    answer = get_object_or_404(Answer, pk=answer_id)
    answer.delete()
    return redirect('board:detail', question_id=answer.question.id)

board/views/base_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from board.models import Question, Answer, Comment
from board.forms import QuestionForm, AnswerForm, CommentForm

def index(request):
    return render(request, 'board/index.html')

def boardlist(request):
    #질문 목록
    #question_list = Question.objects.all()  #db 전체조회

    #페이지 처리
    page = request.GET.get('page', 1)  #127.0.0.1:8000/ 기본 1페이지임
    kw = request.GET.get('kw', '')  # 검색어 가져오기

    #조회
    question_list = Question.objects.order_by('-create_date')#작성일 내림차순
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) | # 제목 검색
            Q(content__icontains=kw) | # 내용 검색
            Q(author__username__icontains=kw) | # 글쓴이 검색
            Q(answer__author__username__icontains=kw) |# 답변 글쓴이
            Q(answer__content__icontains=kw)
        ).distinct()   #유일한 것 검색

    paginator = Paginator(question_list, 10) #페이지당 10개씩 설정
    page_obj = paginator.get_page(page)    #페이지 가져오기
    context = {'question_list':page_obj, 'page':page, 'kw':kw}
    return render(request, 'board/question_list.html', context)

def detail(request, question_id):
    # 질문/답변 상세
    # question = Question.objects.get(id=question_id) #해당 id의 질문
    question = get_object_or_404(Question, pk=question_id)
    #경로에 오류가 있을 때 404로 처리(페이지가 없음)
    return render(request, 'board/detail.html', {'question':question})

templates/board/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <!-- 추천 오류 -->
    {% if messages %}
        {% for message in messages %}
    <div class="alert alert-danger">
            <strong>{{ massage.tags }}</strong>
        <ul>
            <li>{{ message.message }}</li>
        </ul>
        </div>
        {% endfor %}
    {% endif %}
    <div class="row">
        <!-- 추천 영역 -->
        <div class="col-1">
            <div class="bg-light text-center border font-weight-bolder p-3">
                {{ question.voter.count }}
            </div>
            <a href="#" data-uri="{% url 'board:vote_question' question.id %}"
               class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <!-- 질문 영역 -->
        <div class="col-11">
        <div class="card">
            <div class="card-body">
                <div class="card-text" style="white-space:pre-line"> <!--style은 줄바꿈 출력-->
                    {{ question.content }}
                </div>
                <div class="d-flex justify-content-end"><!--오른쪽 정렬-->
                    {% if question.modify_date %}
                    <div class="badge bagde-light text-left p-2">
                        <div class="mb-2">modefied at</div>
                        <div>{{ question.modify_date }}</div>
                    </div>
                    {% endif %}
                    <div class="badge bagde-light text-left p-2">
                        <div class="mb-2">{{ question.author }}</div>
                        <div>{{ question.create_date }}</div>
                    </div>
                </div>
                {% if request.user == question.author %}
                <div>
                    <a href="{% url 'board:question_modify' question.id %}"
                       class="btn btn-sm btn-outline-secondary">수정</a>
                    <a href="#" data-uri="{% url 'board:question_delete' question.id %}"
                       class="delete btn btn-sm btn-outline-secondary">삭제</a>
                </div>
                {% endif %}
                <!--댓글 영역-->
                <div class="mt-3">
                    {% for comment in question.comment_set.all %}
                    <div class="comment my-2 text-muted">
                        <span style="white-space:pre-line">
                            {{ comment.content }}
                        </span>
                        <span>
                            -{{ comment.author }}, {{ comment.create_date }}
                            {% if comment.modify_date %}
                                (수정:{{ comment.modify_date }}
                            {% endif %}
                        </span>
                        {% if request.user == comment.author %}
                        <a href="{% url 'board:comment_modify_question' comment.id %}">수정</a>
                        <a href="#" class="delete"
                            data-uri="{% url 'board:comment_delete_question' comment.id %}">삭제</a>
<!--                        <a onclick=""return confirm('정말로 삭제하시겠습니까?')"-->
<!--                            href= {% url 'board:comment_delete_question' comment.id %}>삭제</a>-->
                        {% endif %}
                    </div>
                    {% endfor %}
                </div>
                <div>
                    <a href="{% url 'board:comment_create_question' question.id %}"
                       class="small">댓글 추가..</a>
                </div>
            </div>
        </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">
        {{ question.answer_set.count }}개의 답변이 있습니다.
    </h5>
    {% for answer in question.answer_set.all %}
    <div class="row my-3">
        <div class="col-1"> <!-- 답변 추천 영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
                {{ answer.voter.count }}
            </div>
            <a href="#" data-uri="{% url 'board:vote_answer' answer.id %}"
               class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
    <div class="col-11">
        <div class="card my-3">
            <div class="card-body">
                <div class="card-text" style="white-space:pre-line">
                    {{ answer.content }}
                </div>
                <div class="d-flex justify-content-end"><!--오른쪽 정렬-->
                    {% if answer.modify_date %}
                    <div class="badge bagde-light text-left p-2">
                        <div class="mb-2">modefied at</div>
                        <div>{{ answer.modify_date }}</div>
                    </div>
                    {% endif %}
                    <div class="badge bagde-light text-left p-2">
                        <div class="mb-2">{{ answer.author }}</div>
                        <div>{{ answer.create_date }}</div>
                    </div>
                </div>
                {% if request.user == answer.author %}
                <div>
                    <a href="{% url 'board:answer_modify' answer.id %}"
                       class="btn btn-sm btn-outline-secondary">수정</a>
                    <a href="#" data-uri="{% url 'board:answer_delete' answer.id %}"
                       class="delete btn btn-sm btn-outline-secondary">삭제</a>
                </div>
                {% endif %}
                <!-- 답변 댓글 시작 -->
                {% if answer.comment_set.count > 0 %}
                <div class="mt-3">
                {% for comment in answer.comment_set.all %}
                    <div class="comment py-2 text-muted">
                        <span style="white-space: pre-line;">{{ comment.content }}</span>
                        <span>
                            - {{ comment.author }}, {{ comment.create_date }}
                            {% if comment.modify_date %}
                            (수정:{{ comment.modify_date }})
                            {% endif %}
                        </span>
                        {% if request.user == comment.author %}
                        <a href="{% url 'board:comment_modify_answer' comment.id %}" class="small">수정</a>
                        <a href="#" class="small delete"
                            data-uri="{% url 'board:comment_delete_answer' comment.id %}">삭제</a>
                        {% endif %}
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
                <div>
                    <a href="{% url 'board:comment_create_answer' answer.id %}" class="small">
                        <small>댓글 추가..</small></a>
                </div>
                <!-- 답변 댓글 끝 -->
            </div>
        </div>
    </div>
</div>
    {% endfor %}
    <form action="{% url 'board:answer_create' question.id %}" method="post">
        {% csrf_token %}
        <!-- 오류 표시 시작 -->
            {% if form.errors %}
            <div class="alert alert-danger">
                {% for field in form %}
                    {% if field.errors %}
                        <strong>{{ field.label }}</strong>
                        {{ field.errors }}
                    {% endif %}
                {% endfor %}
            </div>
            {% endif %}
        <!-- 오류 표시 끝-->
        <div class="form-group">
            <textarea name="content" rows="7" cols="50" class="form-control"
                        {% if not user.is_authenticated %}
                            disabled
                        {% endif %}></textarea>
        </div>
        <input type="submit" value="답변 등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script>
    $(document).ready(function(){
        //삭제 처리
        $(".delete").on('click', function(){
            if(confirm('정말로 삭제하시겠습니까?')){
                location.href = $(this).data('uri')
            }
        });

        //추천 처리
        $(".recommend").on('click', function(){
            if(confirm('정말로 추천하시겠습니까?')){
                location.href= $(this).data('uri');
            }
        });
    });
</script>
{% endblock %}

templates/board/index.html
{% extends 'base.html' %}
{% block content %}
<section>
    <div class="jumbotron">
        <div class="text-center">
            <h1>Welcome~ My Home! Have a Nice Day!</h1>
        </div>
    </div>
    <div class="text-center">
        <img src="../../static/board/images/coffee-gray.jpg">
        <p id="demo" class="my-3"></p>
    </div>
</section>

<script src="../../static/board/js/main_js.js"></script>
{% endblock %}

templates/board/question_list.html
{% extends 'base.html' %}
{% load board_filter %}
{% block content %}
<div class="container my-3">
    <section>
    <!-- 검색 입력 상자와 찾기 버튼 -->
        <div class="row justify-content-end mb-2">
            <div class="col-4 input-group">
                <input type="text" class="kw form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                <button type="button" id="btn_search"
                        class="btn btn-outline-secondary">찾기</button>
                </div>
            </div>
        </div>
    <!-- 게시판 목록 -->
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th>번호</th><th>추천</th><th>제목</th><th>글쓴이</th><th>작성일시</th>
                </tr>
            </thead>
            <tbody>
                {% if question_list %}
                    {% for question in question_list  %}
                    <tr>
    <!--                    <td>{{ forloop.counter }}</td>-->
                        <td>{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}</td>
                        <td>
                            {% if question.voter.all.count > 0 %}
                            <span class="badge badge-warning px-2 py-1">
                                {{ question.voter.all.count }}
                            </span>
                            {% endif %}
                        </td>
                        <td>
                            <!--링크 경로는 앱 네임을 사용함-->
                            <a href="{% url 'board:detail' question.id %}">
                                {{ question.subject }}
                            </a>
                            {% if question.answer_set.count > 0 %}
                              <span class="text-danger small">[{{ question.answer_set.count }}]</span>
                            {% endif %}
                        </td>
                        <td>{{ question.author }}</td>
                        <td>{{ question.create_date }}</td>
                    </tr>
                    {% endfor %}
                {% else %}
                <p>질문이 없습니다.</p>
                {% endif %}
            </tbody>
        </table>
        <!-- 페이징 처리 시작-->
        <ul class="pagination justify-content-center">
            <!-- 이전 페이지 -->
            {% if question_list.has_previous %}
            <li class="page-item">
<!--                <a class="page-link"-->
<!--                   href="?page={{ question_list.previous_page_number }}">이전</a>-->
                <a class="page-link" href="#"
                    data-page="{{ question_list.previous_page_number }}">이전</a>
            </li>
            {% else %} <!-- 이전페이가 없으면(마지막이면) -->
            <li class="page-item disabled">
                <a class="page-link" href="#">이전</a>
            </li>
            {% endif %}

            <!-- 페이지 리스트-->
            {% for page_number in question_list.paginator.page_range %}
                {% if page_number == question_list.number %}
                <li class="page-item active"> <!--번호 활성화-->
<!--                    <a class="page-link"-->
<!--                       href="?page={{ page_number }}">{{ page_number }}</a>-->
                    <a class="page-link" href="#"
                       data-page="{{ page_number }}">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item">
<!--                    <a class="page-link"-->
<!--                       href="?page={{ page_number }}">{{ page_number }}</a>-->
                    <a class="page-link" href="#"
                       data-page="{{ page_number }}">{{ page_number }}</a>
                <!-- 해당 경로의 페이지-->
                </li>
                {% endif %}
            {% endfor %}

            <!-- 다음 페이지 -->
            {% if question_list.has_next %}
            <li class="page-item">
<!--                <a class="page-link"-->
<!--                   href="?page={{ question_list.next_page_number }}">다음</a>-->
                <a class="page-link" href="#"
                data-page="{{ question_list.next_page_number }}">다음</a>
            </li>
            {% else %} <!-- 다음페이지가 없으면(마지막이면) -->
            <li class="page-item disabled">
                <a class="page-link" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
        <!-- 페이징 처리 끝 -->
        <a class="btn btn-primary"
           href="{% url 'board:question_create' %}">질문 등록</a>
        <!-- 검색 폼 만들기 -->
        <form action="" method="get" id="searchForm"> <!-- page, kw 은 get 방식으로 요청 -->
            <input type="hidden" name="kw" id="kw">
            <input type="hidden" name="page" id="page">
        </form>
    </section>
</div>
{% endblock %}
{% block script %}
<script>
    $(document).ready(function(){
        //페이지 처리
        $(".page-link").on('click', function(){     //페이지 번호를 클릭하면
            $("#page").val($(this).data("page"));   //해당 페이지 번호를 page 필드에 가져옴
            $("#searchForm").submit();              //폼을 전송
        });

        //검색 처리
        $("#btn_search").on('click', function(){
            let text = $(".kw").val();     //검색어 값
            $("#kw").val(text);            //폼의 입력 필드에 설정
            $("#page").val(1);             //1페이지를 페이지 필드에 설정
            $("#searchForm").submit();     //폼을 전송
        });
    });
</script>
{% endblock %}